export const Themes = [
  {
    name: "Theme1",
    Background: "bg-Background1",
    KeyPadBackground: "bg-KeyPadBackground1",
    ScreenBackground: "bg-ScreenBackground1",
    OperatorKeyBackground: "bg-OperatorKeyBackground1",
    OperatorKeyShadow: "shadow-OperatorKeyShadow1",
    EqualKeyBackground: "bg-EqualKeyBackground1",
    EqualKeyShadow: "shadow-EqualKeyShadow1",
    KeyBackground: "bg-KeyBackground1",
    KeyShadow: "shadow-KeyShadow1",
    MainText: "text-MainText1",
    SecondaryText: "text-SecondaryText1",
    HoverKey: "hover:bg-KeyHover1",
  },
  {
    name: "Theme2",
    Background: "bg-Background2",
    KeyPadBackground: "bg-KeyPadBackground2",
    ScreenBackground: "bg-ScreenBackground2",
    OperatorKeyBackground: "bg-OperatorKeyBackground2",
    OperatorKeyShadow: "shadow-OperatorKeyShadow2",
    EqualKeyBackground: "bg-EqualKeyBackground2",
    EqualKeyShadow: "shadow-EqualKeyShadow2",
    KeyBackground: "bg-KeyBackground2",
    KeyShadow: "shadow-KeyShadow2",
    MainText: "text-MainText2",
    SecondaryText: "text-SecondaryText2",
  },
  {
    name: "Theme3",
    Background: "bg-Background3",
    KeyPadBackground: "bg-KeyPadBackground3",
    ScreenBackground: "bg-ScreenBackground3",
    OperatorKeyBackground: "bg-OperatorKeyBackground3",
    OperatorKeyShadow: "shadow-OperatorKeyShadow3",
    EqualKeyBackground: "bg-EqualKeyBackground3",
    EqualKeyShadow: "shadow-EqualKeyShadow3",
    KeyBackground: "bg-KeyBackground3",
    KeyShadow: "shadow-KeyShadow3",
    MainText: "text-MainText3",
    SecondaryText: "text-SecondaryText3",
  },
];
